---
- hosts: localhost
  become: yes

  tasks:
    - name: Install python-docker
      apt: pkg=python-docker state=present

    - name: make sure deluge container is running
      docker_container:
        name: deluge
        image: deluge
        network_mode: host
        restart_policy: unless-stopped
        volumes:
          - /tmp:/incomplete
          - /storage/metadata/deluge:/root/.config/deluge
          - /storage:/storage

